apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: 3tier-ns
  labels:
    app: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
     labels:
       app: backend
    spec:
      containers:
        - name: backend-container
          image: rnld101/3tier-nodejs:backend
          ports:
            - containerPort: 3000
          envFrom:
            - ConfigMapRef: 
                name: backend-configmap
