apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: 3tier-ns
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend 
  ports:
    - port: 80
      targetPort: 3000